# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```


In [6]:
import numpy as pd
import numpy as pd

In [12]:
a=pd.linspace(1,10,10)
print(a)




[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


b
---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [19]:
a = pd.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```


In [40]:
a=pd.linspace(1,5,10,endpoint=False)
print(a)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [17]:

d = pd.eye(5)         
print(d)             
    

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```


In [42]:
d = pd.random.rand(4,4)     
print(d)             
    

[[0.23570772 0.36289702 0.24502784 0.81324274]
 [0.59993608 0.38938455 0.49517025 0.69347223]
 [0.46012537 0.45933493 0.53578611 0.05424111]
 [0.84449706 0.07427624 0.06659208 0.29255448]]




---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```


In [31]:
d.shape

(4, 4)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```


In [44]:
d = pd.random.random((16))  
q = pd.random.seed((10)) 
print(q) 
print(d)

None
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607]


In [45]:
d = pd.random.random((16))  
q = pd.random.seed((0)) 
print(q) 
print(d)

None
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607]


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```


In [52]:
d = pd.arange(16) 
d
d.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```


In [53]:
d.dtype

dtype('int32')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```


In [66]:

q=pd.arange(2,101,2)
q


#A=[x for x in pd.arange(1,101) if x%2==0]


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [77]:
# 10
w=pd.random.randint(10,50,(6,6))
w

array([[22, 13, 29, 21, 11, 16],
       [23, 40, 45, 10, 37, 12],
       [35, 44, 21, 14, 43, 24],
       [41, 38, 32, 22, 23, 43],
       [23, 16, 15, 46, 35, 14],
       [30, 24, 25, 39, 23, 27]])

array([[34, 37, 19, 18],
       [46, 41, 22, 39],
       [14, 12, 28, 44]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [82]:
w=pd.random.randint(10,50,(4,4))
w[:3:]

array([[33, 15, 33, 49],
       [21, 35, 40, 25],
       [33, 48, 46, 29]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [83]:
d = pd.arange(16) 
print(pd.sum(d)) 

120


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [85]:
pd.mean(d)
pd.median(d)
pd.std(d)

4.6097722286464435

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [89]:
pd.max(d)


15

In [90]:
pd.min(d)

0

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [102]:
p=pd.random.randint(0,100,20)
pd.argmax(p)

14

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [111]:
p=pd.random.randint(0,100,20)
print(p)
print("ooooooooooooooooooooooooooooo")
q=p[::-1]
print(q)


[ 8 63 16  8 43 48 10 68 98 73 42 36 15 28  6 91  1 19 11  5]
ooooooooooooooooooooooooooooo
[ 5 11 19  1 91  6 28 15 36 42 73 98 68 10 48 43  8 16 63  8]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [118]:
q=pd.random.randint(0,10,(3,3))
print(q)
print("PPPPPPPPP")
p=pd.random.randint(10,100,(3,3))

print(p)
print("PPPPPPPPP")
w=print(pd.multiply(q,p))

[[4 5 2]
 [9 3 2]
 [5 3 3]]
PPPPPPPPP
[[53 83 21]
 [41 27 99]
 [20 82 89]]
PPPPPPPPP
[[212 415  42]
 [369  81 198]
 [100 246 267]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [124]:
q=pd.arange(3,8)
pd.diag(q)

array([[3, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [128]:
q=pd.arange(3,7)
w=pd.arange(7,11)
p1=pd.diag(q)
p2=pd.diag(w)
m=p1@p2
Q=pd.dot(p1,p2)
print(q)
print("rrrrrrrrrrr")
print(w)
print("rrrrrrrrrrr")
print(m)
print(Q)

[3 4 5 6]
rrrrrrrrrrr
[ 7  8  9 10]
rrrrrrrrrrr
[[21  0  0  0]
 [ 0 32  0  0]
 [ 0  0 45  0]
 [ 0  0  0 60]]
[[21  0  0  0]
 [ 0 32  0  0]
 [ 0  0 45  0]
 [ 0  0  0 60]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [143]:
q=pd.arange(3,7)
p1=pd.diag(q)
p1.reshape(1,16)

array([[3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5, 0, 0, 0, 0, 6]])

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [162]:
q = pd.arange(3, 7)
x = pd.arange(3, 7)
m = q.reshape(4, 1)
n = x.reshape(4, 1)
result = pd.column_stack((m, n))
print(result)


[[3 3]
 [4 4]
 [5 5]
 [6 6]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [168]:
q = pd.arange(3, 7)
x = pd.arange(3, 7)
m = q.reshape(1, 4)  
n = x.reshape(1, 4)  
result = pd.hstack((m, n))
print(result)


[[3 4 5 6 3 4 5 6]]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [170]:
a = pd.arange(10)
result = np.split(a, 5)
print(result)


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [172]:
r = pd.random.rand(3,3)
a = pd.round(r, 2)

print(a)

[[0.22 0.88 0.87]
 [0.01 0.3  0.74]
 [0.7  0.38 0.32]]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [174]:
a = pd.array([1, 2, 2,  4, 4, 5])
u = pd.unique(a)
print(u)

[1 2 4 5]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [178]:
a = pd.random.rand(5)
v = 5
a[a < v] = 9

print(a)


[9. 9. 9. 9. 9.]


```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [180]:
a = pd.array([6, 2, 0, 4, 5])
c = pd.cumsum(a)

print(c)


[ 6  8  8 12 17]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [181]:
a = pd.array([0, 1, 2, 0, 3, 4, 0])
n = pd.count_nonzero(a)

print(n)

4


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [13]:
a = pd.random.randint(1,100,10)
s = pd.sort(a)
print(s)


[ 2  5 21 31 35 49 54 57 89 98]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [17]:
a = pd.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r= pd.sum(a, axis=1)
c= pd.sum(a, axis=0)
print(a)
print("Row:", r)
print("Column:", c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row: [ 6 15 24]
Column: [12 15 18]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [19]:
a = pd.random.rand(3, 3)
n = (a - a.min()) / (a.max() - a.min())
print(n)


[[0.         0.98608483 0.21345673]
 [0.27442403 0.41524796 0.8842512 ]
 [0.61869739 1.         0.20747448]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [21]:
a = pd.array([1, 2,3])
b = pd.array([4,5, 6])
dot= pd.dot(a, b)

print(dot)

32


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [22]:
a = pd.array([[1,2, 3], [4, 5,6], [7, 8,9]])
t= pd.trace(a)

print(t)


15


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [23]:
a = pd.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[[0, 2]] = a[[2, 0]]
print(a)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [29]:
a = pd.array([1, 2, 3, 4, 5])
r = pd.column_stack((a))
c= a.reshape(-1, 1)

print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]


---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [31]:
a = pd.array([[1,2,3], [4, 5,6], [7,8,9]])
d= pd.linalg.det(a)
print(d)


-9.51619735392994e-16


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [34]:
a = pd.array([[4, 2], [1, 3]])
value=pd.linalg.eig(a)

print("Eigen values:",value)


Eigen values: EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [35]:
A = pd.array([[2, 3], [4, 1]])
b = pd.array([8, 10])
sol= pd.linalg.solve(A, b)

print("Solution:",sol)


Solution: [2.2 1.2]


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [38]:
a = pd.array([1, 2, 3, 4, 5])
noise = pd.random.normal(0, 0.1, a.shape)
n = a+noise
print(n)


[0.98149094 2.00127015 2.95629268 4.06301227 5.01842126]


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [41]:
a = pd.array([[1,2,3,4],[5,6,7,8], [9,10,11,12],[13,14,15,16]])
d= pd.diagonal(a)
print(d)

[ 1  6 11 16]


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

In [43]:
a = pd.random.rand(100)   
c= pd.clip(a, 10, 50)
print(c)


[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

In [44]:
a = pd.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
a[a < 0] = 0
print(a)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

In [45]:
dtype = pd.dtype([('name', 'U20'), ('age', 'i4'), ('height', 'f4')])
data = pd.array([(b'Alice', 25, 5.6),  (b'Bob', 30, 5.8),  (b'Charlie', 22, 5.5)], dtype=dtype)
print(data)


[('Alice', 25, 5.6) ('Bob', 30, 5.8) ('Charlie', 22, 5.5)]


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

In [52]:
matrix = pd.random.randint(0,10,(5, 5))
u= pd.unique(matrix, return_counts=True)
oc = pd.array(list(zip(u)))
print(matrix)
print(oc)


[[6 6 5 9 6]
 [0 9 9 1 6]
 [5 0 4 3 0]
 [3 1 3 4 7]
 [4 2 5 4 7]]
[[[0 1 2 3 4 5 6 7 9]]

 [[3 2 1 3 4 3 4 2 3]]]


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

In [53]:
a = pd.random.randint(0, 100,10)
an=(a > 50).any()
print(a)
print("values greater than 50:", an)


[60 72 46 42 91 29 65  7 39 25]
values greater than 50: True


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
`

In [57]:
a = pd.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
size=3
mov= pd.convolve(a,pd.array([1/size]*size), mode='valid')
print("Original:",a)
print(a)
print("\n average:",mov)


Original: [ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]

 average: [2. 3. 4. 5. 6. 7. 8. 9.]


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
`

In [60]:
x = pd.array([1,2, 3,4,5])
y = pd.array([5,4,3, 2,1])
matrix = pd.corrcoef(x, y)
corr =matrix[0,1]

print("corr coefficient:",corr)


corr coefficient: -0.9999999999999999


---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

In [62]:
rad=pd.array([0, pd.pi/4, pd.pi/2, pd.pi, 3*pd.pi/2, 2*pd.pi])
degrees=pd.degrees(rad)
print(rad)
print(degrees)


[0.         0.78539816 1.57079633 3.14159265 4.71238898 6.28318531]
[  0.  45.  90. 180. 270. 360.]





---

---


---


---



```python
# Exercise 20
```


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---
